from typing import Callable, Optional, Union


class CookieDict:
    @property
    def name(self) -> str: ...

    @property
    def value(self) -> str: ...

    @property
    def domain(self) -> Optional[str]: ...

    @property
    def path(self) -> Optional[str]: ...

    @property
    def secure(self) -> bool: ...

    @property
    def http_only(self) -> bool: ...


class WebView:
    def __init__(
            self,
            parent_hwnd: int,
            *,
            width: int = 800,
            height: int = 600,
            url: Optional[str] = None,
            html: Optional[str] = None,
            transparent: bool = False,
            background_color: Optional[tuple[int, int, int, int]] = None,
            visible: bool = True,
            devtools: bool = False,
            incognito: bool = False,
            user_agent: Optional[str] = None,
            focused: bool = True,
            autoplay: bool = False,
            javascript_enabled: bool = True,
            hotkeys_zoom: bool = True,
            initialization_script: Optional[str] = None,
            ipc_handler: Optional[Callable[[str], None]] = None,
            on_navigation: Optional[Callable[[str], bool]] = None,
            on_page_load: Optional[Callable[[str, str], None]] = None,
            on_title_changed: Optional[Callable[[str], None]] = None,
            on_new_window: Optional[Callable[[str], str]] = None,
            drag_drop_handler: Optional[Callable[[str, list[str], tuple[int, int]], bool]] = None,
            custom_protocols: Optional[
                dict[str, Callable[[str, str, list[tuple[str, str]], bytes, Callable[[int, list[tuple[str, str]], bytes], None]], None]]
            ] = None,
            proxy: Optional[dict[str, str]] = None,
            back_forward_gestures: bool = False,
            clipboard: bool = True,
            data_directory: Optional[str] = None,
            headers: Optional[Union[dict[str, str], list[tuple[str, str]]]] = None,
    ) -> None: ...

    def load_url(self, url: str) -> None: ...

    def load_url_with_headers(self, url: str, headers: Union[dict[str, str], list[tuple[str, str]]]) -> None: ...

    def load_html(self, html: str) -> None: ...

    def reload(self) -> None: ...

    def url(self) -> Optional[str]: ...

    def eval_js(self, script: str) -> None: ...

    def eval_js_with_callback(self, script: str, callback: Callable[[str], None]) -> None: ...

    def set_ipc_handler(self, handler: Callable[[str], None]) -> None: ...

    def clear_ipc_handler(self) -> None: ...

    def set_on_navigation(self, handler: Callable[[str], bool]) -> None: ...

    def set_on_page_load(self, handler: Callable[[str, str], None]) -> None: ...

    def set_on_title_changed(self, handler: Callable[[str], None]) -> None: ...

    def set_on_new_window(self, handler: Callable[[str], str]) -> None: ...

    def set_drag_drop_handler(self, handler: Callable[[str, list[str], tuple[int, int]], bool]) -> None: ...

    def set_bounds(self, x: float, y: float, width: float, height: float) -> None: ...

    def bounds(self) -> Optional[tuple[float, float, float, float]]: ...

    def set_visible(self, visible: bool) -> None: ...

    def set_background_color(self, r: int, g: int, b: int, a: int) -> None: ...

    def focus(self) -> None: ...

    def zoom(self, scale: float) -> None: ...

    def open_devtools(self) -> None: ...

    def close_devtools(self) -> None: ...

    def is_devtools_open(self) -> bool: ...

    def cookies(self) -> list[CookieDict]: ...

    def cookies_for_url(self, url: str) -> list[CookieDict]: ...

    def set_cookie(self, name: str, value: str, domain: Optional[str] = None, path: Optional[str] = None) -> None: ...

    def delete_cookie(self, name: str, url: str) -> None: ...

    def print(self) -> None: ...

    def clear_all_browsing_data(self) -> None: ...
